// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://noygjlupszcqtfkztomt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5veWdqbHVwc3pjcXRma3p0b210Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MTkyNTEsImV4cCI6MjA2ODM5NTI1MX0.blkiWEOkiKdicL7J4Wq1161RF9BYBBDMu-bUeffeZDo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});